// <auto-generated />
using System;
using DataAcesss;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAcesss.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221030205002_AddedPostLikes")]
    partial class AddedPostLikes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DataAcesss.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("ClanId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ClanId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6",
                            AccessFailedCount = 0,
                            ClanId = 1,
                            ConcurrencyStamp = "77dd27c4-8531-4741-9231-2c0d859d0c09",
                            Email = "drazen.marinkovic1@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Dražen",
                            LastName = "Marinković",
                            LockoutEnabled = true,
                            NormalizedEmail = "DRAZEN.MARINKOVIC1@GMAIL.COM",
                            NormalizedUserName = "DMARINKOVIC",
                            PasswordHash = "AQAAAAEAACcQAAAAELAPlQf8sVUM/Sc31lIipH7sBfuUsCGeZawx2x0YYRl4pDu1viNlCOk4SEiznbNjlw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "QSJGIOPEXML4J3IXUW3PVXBZ7GB5YN46",
                            TwoFactorEnabled = false,
                            UserName = "dmarinkovic"
                        },
                        new
                        {
                            Id = "45a0f303-506b-4a0e-b42f-0b1c814d84f7",
                            AccessFailedCount = 0,
                            ClanId = 2,
                            ConcurrencyStamp = "77dd27c4-8531-4741-9231-2c0d859d0c09",
                            Email = "tomislav.berisic@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Tomislav",
                            LastName = "Berišić",
                            LockoutEnabled = true,
                            NormalizedEmail = "TOMISLAV.BERISIC@GMAIL.COM",
                            NormalizedUserName = "TBERISIC",
                            PasswordHash = "AQAAAAEAACcQAAAAECCRKBsGtZvndBuz9iFwly0sqK8/vI/2GskOb/RMBxQYQXXu/ZUBlmXye+qZ+PMxjg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "QSJGIOPEXML4J3IXUW3PVXBZ7GB5YN46",
                            TwoFactorEnabled = false,
                            UserName = "tberisic"
                        },
                        new
                        {
                            Id = "d2b416d1-7861-4d6e-835e-4e1ebc65ce7b",
                            AccessFailedCount = 0,
                            ClanId = 2,
                            ConcurrencyStamp = "77dd27c4-8531-4741-9231-2c0d859d0c09",
                            Email = "test@test.com",
                            EmailConfirmed = false,
                            FirstName = "Pero",
                            LastName = "Perić",
                            LockoutEnabled = true,
                            NormalizedEmail = "TEST@TEST.COM",
                            NormalizedUserName = "KORISNIK",
                            PasswordHash = "AQAAAAEAACcQAAAAECCRKBsGtZvndBuz9iFwly0sqK8/vI/2GskOb/RMBxQYQXXu/ZUBlmXye+qZ+PMxjg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "QSJGIOPEXML4J3IXUW3PVXBZ7GB5YN46",
                            TwoFactorEnabled = false,
                            UserName = "korisnik"
                        });
                });

            modelBuilder.Entity("DataAcesss.Data.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"), 1L, 1);

                    b.Property<DateTime>("LogDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("LogType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("DataAcesss.Data.Bet", b =>
                {
                    b.Property<int>("BetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BetId"), 1L, 1);

                    b.Property<decimal>("BetCoeficient")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BetDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("BetType")
                        .HasColumnType("int");

                    b.Property<bool>("IsWinningBet")
                        .HasColumnType("bit");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BetId");

                    b.HasIndex("MatchId");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("DataAcesss.Data.ChatLike", b =>
                {
                    b.Property<int>("LikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LikeId"), 1L, 1);

                    b.Property<DateTime>("LikeDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LikeId");

                    b.HasIndex("PostId");

                    b.ToTable("ChatLikes");
                });

            modelBuilder.Entity("DataAcesss.Data.ChatPost", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"), 1L, 1);

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PostDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalLikes")
                        .HasColumnType("int");

                    b.HasKey("PostId");

                    b.ToTable("ChatPosts");
                });

            modelBuilder.Entity("DataAcesss.Data.ChatReply", b =>
                {
                    b.Property<int>("ReplyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReplyId"), 1L, 1);

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReplyDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("ReplyId");

                    b.HasIndex("PostId");

                    b.ToTable("ChatReplies");
                });

            modelBuilder.Entity("DataAcesss.Data.Clan", b =>
                {
                    b.Property<int>("ClanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClanId"), 1L, 1);

                    b.Property<DateTime>("ClanDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ClanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClanId");

                    b.HasIndex("ClanName")
                        .IsUnique();

                    b.ToTable("Clans");

                    b.HasData(
                        new
                        {
                            ClanId = 1,
                            ClanDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClanName = "HRPRO",
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            ClanId = 2,
                            ClanDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClanName = "Erste",
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        });
                });

            modelBuilder.Entity("DataAcesss.Data.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"), 1L, 1);

                    b.Property<decimal>("CountryCoeficient")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CountryDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.HasIndex("CountryName")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "Katar",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            CountryId = 2,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "Ekvador",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            CountryId = 3,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "Senegal",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            CountryId = 4,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "Nizozemska",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            CountryId = 5,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "Engleska",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            CountryId = 6,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "Iran",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            CountryId = 7,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "SAD",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            CountryId = 8,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "Wales",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            CountryId = 9,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "Argentina",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            CountryId = 10,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "Saudijska Arabija",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            CountryId = 11,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "Meksiko",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            CountryId = 12,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "Poljska",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            CountryId = 13,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "Francuska",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            CountryId = 14,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "Australija",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            CountryId = 15,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "Danska",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            CountryId = 16,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "Tunis",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            CountryId = 17,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "Španjolska",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            CountryId = 18,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "Kostarika",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            CountryId = 19,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "Njemačka",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            CountryId = 20,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "Japan",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            CountryId = 21,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "Belgija",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            CountryId = 22,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "Kanada",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            CountryId = 23,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "Maroko",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            CountryId = 24,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "Hrvatska",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            CountryId = 25,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "Brazil",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            CountryId = 26,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "Srbija",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            CountryId = 27,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "Švicarska",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            CountryId = 28,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "Kamerun",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            CountryId = 29,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "Portugal",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            CountryId = 30,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "Gana",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            CountryId = 31,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "Urugvaj",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        },
                        new
                        {
                            CountryId = 32,
                            CountryCoeficient = 0m,
                            CountryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryName = "Južna Koreja",
                            IsWinner = false,
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6"
                        });
                });

            modelBuilder.Entity("DataAcesss.Data.CountryBet", b =>
                {
                    b.Property<int>("CountryBetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryBetId"), 1L, 1);

                    b.Property<DateTime>("CountryBetDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<decimal>("CountryCoeficient")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsWinningBet")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryBetId");

                    b.HasIndex("CountryId");

                    b.ToTable("CountryBets");
                });

            modelBuilder.Entity("DataAcesss.Data.ErrorLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"), 1L, 1);

                    b.Property<string>("AdditionalInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallSite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InnerException")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LogDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("DataAcesss.Data.EventLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"), 1L, 1);

                    b.Property<string>("EventType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LogDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<string>("TableField")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("EventLogs");
                });

            modelBuilder.Entity("DataAcesss.Data.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchId"), 1L, 1);

                    b.Property<decimal>("AwayCoeficient")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DrawCoeficient")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HomeCoeficient")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MatchDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("MatchDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WinningBetType")
                        .HasColumnType("int");

                    b.HasKey("MatchId");

                    b.HasIndex("WebId")
                        .IsUnique();

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "7502b3fd-40fb-4a4a-ace8-647270657934",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "8ea6ca95-5ede-4b33-ac3f-add02baaf091",
                            Name = "Korisnik",
                            NormalizedName = "Korisnik"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "4009d724-f1e3-46ab-b58b-ad78a0f8a1f6",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "45a0f303-506b-4a0e-b42f-0b1c814d84f7",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "d2b416d1-7861-4d6e-835e-4e1ebc65ce7b",
                            RoleId = "2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Models.ViewModels.ClanStatsVM+ClanStatsAbs", b =>
                {
                    b.Property<string>("ClanName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WinningBetsCount")
                        .HasColumnType("int");

                    b.ToTable("ClanStatsAbs");
                });

            modelBuilder.Entity("Models.ViewModels.ClanStatsVM+ClanStatsPercentage", b =>
                {
                    b.Property<decimal>("AvgCoeficient")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClanName")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ClanStats");
                });

            modelBuilder.Entity("Models.ViewModels.ClanStatsVM+ClanUsers", b =>
                {
                    b.Property<string>("ClanName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsersCount")
                        .HasColumnType("int");

                    b.ToTable("ClanUsers");
                });

            modelBuilder.Entity("Models.ViewModels.GeneralStatsVM+WinsPerDay", b =>
                {
                    b.Property<DateTime>("MatchDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("WinnersCount")
                        .HasColumnType("int");

                    b.ToTable("WinsPerDay");
                });

            modelBuilder.Entity("Models.ViewModels.LeaderBoardVM", b =>
                {
                    b.Property<string>("ClanName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCoeficient")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("LeaderBoard");
                });

            modelBuilder.Entity("Models.ViewModels.MatchResultsVM", b =>
                {
                    b.Property<string>("AwayTeam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeTeam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MatchDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WinnersCount")
                        .HasColumnType("int");

                    b.ToTable("MatchResults");
                });

            modelBuilder.Entity("Models.ViewModels.MyStatsGridVM", b =>
                {
                    b.Property<string>("AwayTeam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BetCoeficient")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BetType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeTeam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsWinningBet")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MatchDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("MyBetList");
                });

            modelBuilder.Entity("Models.ViewModels.MyStatsVM", b =>
                {
                    b.Property<decimal?>("BestWinningCoeficient")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClanName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TotalBetCount")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WinningBetCount")
                        .HasColumnType("int");

                    b.ToTable("MyStats");
                });

            modelBuilder.Entity("Models.ViewModels.UsersPerClanVM", b =>
                {
                    b.Property<int>("ClanId")
                        .HasColumnType("int");

                    b.Property<string>("ClanName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsersPerClan")
                        .HasColumnType("int");

                    b.ToTable("UsersPerClan");
                });

            modelBuilder.Entity("DataAcesss.Data.ApplicationUser", b =>
                {
                    b.HasOne("DataAcesss.Data.Clan", "Clan")
                        .WithMany()
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clan");
                });

            modelBuilder.Entity("DataAcesss.Data.Bet", b =>
                {
                    b.HasOne("DataAcesss.Data.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("DataAcesss.Data.ChatLike", b =>
                {
                    b.HasOne("DataAcesss.Data.ChatPost", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("DataAcesss.Data.ChatReply", b =>
                {
                    b.HasOne("DataAcesss.Data.ChatPost", "ChatPost")
                        .WithMany()
                        .HasForeignKey("PostId");

                    b.Navigation("ChatPost");
                });

            modelBuilder.Entity("DataAcesss.Data.CountryBet", b =>
                {
                    b.HasOne("DataAcesss.Data.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DataAcesss.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DataAcesss.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAcesss.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DataAcesss.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
